name: Update README with latest blog posts

on:
  schedule:
    - cron: '0 * * * *'   # hourly (UTC)
  workflow_dispatch:        # manual trigger

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.sqlmaps.com/atom.xml"
          max_post_count: 5
